# ***Predicting WBK Clients Status with Neural Network***

In [365]:
import pandas                  as pd
import numpy                   as np
from   sklearn.model_selection import train_test_split
from   sklearn.metrics         import confusion_matrix, accuracy_score
from   sklearn.preprocessing   import LabelEncoder, OneHotEncoder
from   keras.models            import Sequential
from   keras.layers            import Dense, Dropout, LSTM
from   keras.utils             import np_utils

In [366]:
df = pd.read_csv('./WBKClientsTreated.csv')
df.shape

(250, 22)

In [367]:
df.head()

Client State Sex  Duration         CreditHistory  Purpose  \
0  Adelina Buenaventura    RJ   M         2  Adelina Buenaventura        2   
1          Adelino Gago    RJ   M         3          Adelino Gago        1   
2         Adélio Lisboa    SE   M         4         Adélio Lisboa        2   
3         Adérito Bahía    MA   M         5         Adérito Bahía        3   
4       Adolfo Patrício    PE   M         6       Adolfo Patrício        2   

   Value  Investment  Job  InstallmentTime  ...  EesidenceSince  Age  \
0      1        5951    2              3.0  ...               3  2.0   
1      2        2096    2              4.0  ...               3  3.0   
2      3        7882    2              4.0  ...               4  4.0   
3      4        4870    2              3.0  ...               3  4.0   
4      2        9055    1              3.0  ...               3  4.0   

   OtherFinance  Housing  ExistingLoan  Profession  Dependents  SocioCompany  \
0            22        3           1.0           1           4             1   
1            49        3           1.0           1           3             2   
2            45        3           2.0           1           4             2   
3            53        3           2.0           2           4             2   
4            35        3           2.0           1           3             2   

   Foreign  Status  
0        0       0  
1        0       0  
2        0       0  
3        0       0  
4        1       0  

[5 rows x 22 columns]

### Getting dataframe values

In [368]:
data = df.iloc[:, 3:].values
target = df.iloc[:, 21].values

print(f'DATA: {data[0]}\n\nTARGET: {target[0]}')

DATA: [2 'Adelina Buenaventura' 2 1 5951 2 3.0 2 1 3 2.0 22 3 1.0 1 4 1 0 0]

TARGET: 0


### LabelEncoder on `CreditHistory`

In [369]:
labelencoder = LabelEncoder()

data[:, 1] = labelencoder.fit_transform(data[:, 1])
data[:, 1]

array([0, 1, 4, 5, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 35, 25, 26, 27, 28, 30, 29, 31, 33, 32, 34,
       36, 37, 38, 39, 40, 41, 42, 43, 59, 44, 45, 46, 47, 48, 49, 52, 50,
       51, 56, 53, 57, 54, 55, 58, 72, 60, 99, 100, 61, 62, 63, 64, 65,
       66, 67, 96, 97, 98, 68, 69, 70, 71, 73, 74, 101, 75, 76, 77, 78,
       79, 81, 82, 83, 80, 84, 86, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       102, 103, 104, 105, 106, 107, 108, 127, 128, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 129, 130, 137, 131, 132, 133, 134, 135, 136, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 175, 176, 168, 169, 173, 174, 170, 171, 172, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 20

In [370]:
data = np.asarray(data).astype(np.float32)

### Formating the target to DUMMY

In [371]:
uniques, quant = np.unique(df['Status'], return_counts = True)
print(f'UNIQUES: {uniques}\nQUANT: {quant}')

UNIQUES: [0 1]
QUANT: [240  10]


In [372]:
target_dummy = np_utils.to_categorical(target)
target_dummy

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

### Separating TRAIN and TEST data

In [373]:
X_train, X_test, y_train, y_test = train_test_split(data, target_dummy,
                                                    test_size = 0.2,
                                                    random_state = 0)

print(len(X_train), len(X_test), len(y_train), len(y_test))

200 50 200 50


In [374]:
y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

## ***Structuring the Neural Network***
> ### `19 - 18 - 2`

In [375]:
model = Sequential()


model.add(Dense(units = 18, input_dim = 19))

# model.add(Dense(units = 17))

model.add(Dense(units = 2, activation = 'softmax'))

In [376]:
model.summary()

Model: "sequential_28"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_76 (Dense)            (None, 18)                360       
                                                                 
 dense_77 (Dense)            (None, 2)                 38        
                                                                 
Total params: 398
Trainable params: 398
Non-trainable params: 0
_________________________________________________________________


### Compiling model

In [377]:
model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(X_train, y_train, epochs = 500, validation_data = (X_test, y_test))

Epoch 1/500
7/7 [==============================] - 0s 17ms/step - loss: 71.6050 - accuracy: 0.9600 - val_loss: 51.2015 - val_accuracy: 0.9600
Epoch 2/500
7/7 [==============================] - 0s 4ms/step - loss: 65.5976 - accuracy: 0.9600 - val_loss: 46.4232 - val_accuracy: 0.9600
Epoch 3/500
7/7 [==============================] - 0s 4ms/step - loss: 58.2035 - accuracy: 0.9600 - val_loss: 42.1039 - val_accuracy: 0.9600
Epoch 4/500
7/7 [==============================] - 0s 4ms/step - loss: 53.0024 - accuracy: 0.9600 - val_loss: 37.4721 - val_accuracy: 0.9600
Epoch 5/500
7/7 [==============================] - 0s 4ms/step - loss: 47.8289 - accuracy: 0.9600 - val_loss: 33.1801 - val_accuracy: 0.9600
Epoch 6/500
7/7 [==============================] - 0s 4ms/step - loss: 41.2418 - accuracy: 0.9600 - val_loss: 29.8125 - val_accuracy: 0.9600
Epoch 7/500
7/7 [==============================] - 0s 4ms/step - loss: 36.8230 - accuracy: 0.9600 - val_loss: 26.3263 - val_accuracy: 0.9600
Epoch 8/500


### Predictions

In [378]:
predictions = model.predict(X_test)
predictions = (predictions > 0.5)
predictions

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ Tr

### Adjusting `y_test` and `predictions` for the Confusion Matrix

In [379]:
y_test_matrix = [np.argmax(t) for t in y_test]
y_prediction_matrix = [np.argmax(t) for t in predictions]

### Confusion Matrix

In [380]:
confusion_matrix(y_test_matrix, y_prediction_matrix)

array([[48,  0],
       [ 0,  2]], dtype=int64)

### Model Accuracy

In [381]:
print(f'ACCURACY: {accuracy_score(y_test_matrix, y_prediction_matrix) * 100:.0f}%')

# GOOD PERFORMANCE

ACCURACY: 100%
