# ***Predicting WBK Clients Status with Neural Network***

In [68]:
import pandas                  as pd
import numpy                   as np
from   sklearn.model_selection import train_test_split
from   sklearn.metrics         import confusion_matrix, accuracy_score
from   keras.models            import Sequential
from   keras.layers            import Dense
from   keras.utils             import np_utils

In [69]:
df = pd.read_csv('./WBKClientsTreated.csv')
df.shape

(250, 20)

In [70]:
df.head()

Client State Sex  Purpose  Value  Investment  Job  \
0  Adelina Buenaventura    RJ   M        2      1        5951    2   
1          Adelino Gago    RJ   M        1      2        2096    2   
2         Adélio Lisboa    SE   M        2      3        7882    2   
3         Adérito Bahía    MA   M        3      4        4870    2   
4       Adolfo Patrício    PE   M        2      2        9055    1   

   InstallmentTime  MaritalState  Fiador  EesidenceSince  Age  OtherFinance  \
0              3.0             2       1               3  2.0            22   
1              4.0             2       4               3  3.0            49   
2              4.0             2       4               4  4.0            45   
3              3.0             3       4               3  4.0            53   
4              3.0             2       4               3  4.0            35   

   Housing  ExistingLoan  Profession  Dependents  SocioCompany  Foreign  \
0        3           1.0           1           4             1        0   
1        3           1.0           1           3             2        0   
2        3           2.0           1           4             2        0   
3        3           2.0           2           4             2        0   
4        3           2.0           1           3             2        1   

   Status  
0       0  
1       0  
2       0  
3       0  
4       0

### Getting dataframe values

In [71]:
data = df.iloc[:, 3:].values
target = df.iloc[:, 19].values

print(f'DATA: {data}\n\nTARGET: {target}')

DATA: [[2.000e+00 1.000e+00 5.951e+03 ... 1.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 2.000e+00 2.096e+03 ... 2.000e+00 0.000e+00 0.000e+00]
 [2.000e+00 3.000e+00 7.882e+03 ... 2.000e+00 0.000e+00 0.000e+00]
 ...
 [1.000e+00 1.000e+00 2.684e+03 ... 1.000e+00 0.000e+00 0.000e+00]
 [5.000e+00 1.000e+00 2.149e+03 ... 1.000e+00 0.000e+00 0.000e+00]
 [2.000e+00 5.000e+00 3.812e+03 ... 1.000e+00 1.000e+00 0.000e+00]]

TARGET: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]


### Formating the target to DUMMY

In [72]:
target_dummy = np_utils.to_categorical(target)
target_dummy

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

### Separating TRAIN and TEST data

In [73]:
X_train, X_test, y_train, y_test = train_test_split(data, target_dummy,
                                                    test_size = 0.3,
                                                    random_state = 0)

print(len(X_train), len(X_test), len(y_train), len(y_test))

175 75 175 75


In [74]:
y_test

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

## ***Structuring the Neural Network***
> ### `16 - 15 - 2`

In [75]:
model = Sequential()


model.add(Dense(units = 15, input_dim = 17))

model.add(Dense(units = 15))

model.add(Dense(units = 2, activation = 'softmax'))

In [76]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 15)                270       
                                                                 
 dense_19 (Dense)            (None, 15)                240       
                                                                 
 dense_20 (Dense)            (None, 2)                 32        
                                                                 
Total params: 542
Trainable params: 542
Non-trainable params: 0
_________________________________________________________________


### Compiling model

In [82]:
model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(X_train, y_train, epochs = 500, validation_data = (X_test, y_test))

Epoch 1/500
6/6 [==============================] - 0s 20ms/step - loss: 2.9316 - accuracy: 0.9029 - val_loss: 4.4887 - val_accuracy: 0.9600
Epoch 2/500
6/6 [==============================] - 0s 5ms/step - loss: 5.7471 - accuracy: 0.9600 - val_loss: 4.7133 - val_accuracy: 0.9600
Epoch 3/500
6/6 [==============================] - 0s 5ms/step - loss: 5.6563 - accuracy: 0.9600 - val_loss: 3.4528 - val_accuracy: 0.9600
Epoch 4/500
6/6 [==============================] - 0s 6ms/step - loss: 3.2218 - accuracy: 0.9600 - val_loss: 1.5856 - val_accuracy: 0.9600
Epoch 5/500
6/6 [==============================] - 0s 5ms/step - loss: 1.9542 - accuracy: 0.8800 - val_loss: 0.1811 - val_accuracy: 0.9867
Epoch 6/500
6/6 [==============================] - 0s 6ms/step - loss: 1.9785 - accuracy: 0.9657 - val_loss: 2.6105 - val_accuracy: 0.9600
Epoch 7/500
6/6 [==============================] - 0s 5ms/step - loss: 3.9682 - accuracy: 0.9600 - val_loss: 3.2501 - val_accuracy: 0.9600
Epoch 8/500
6/6 [=========

### Predictions

In [83]:
predictions = model.predict(X_test)
predictions = (predictions > 0.5)
predictions

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ Tr

### Adjusting `y_test` and `predictions` for the Confusion Matrix

In [84]:
y_test_matrix = [np.argmax(t) for t in y_test]
y_prediction_matrix = [np.argmax(t) for t in predictions]

### Confusion Matrix

In [85]:
confusion_matrix(y_test_matrix, y_prediction_matrix)

array([[72,  0],
       [ 1,  2]], dtype=int64)

### Model Accuracy

In [86]:
print(f'ACCURACY: {accuracy_score(y_test_matrix, y_prediction_matrix) * 100:.0f}%')

# GOOD PERFORMANCE

ACCURACY: 99%
